#REFERÊNCIA ENTRE OBJETOS NA MEMÓRIA
#UMA CLASSE PODE TER MAIS DE UMA OU VÁRIAS INSTÂNCIAS DE OBJETOS NA MEMÓRIA.
#AGREGAÇÃO: PARA ATENDER A NOVAS NECESSIDADES DO SISTEMA DE CONTA CORRENTE DO BANCO, COM FUNCIONALIDADES PARA O GERENCIMANEOT DE CONTA CONJUNTA, OU SEJA, UMA CONTA CORRENTE PODE TER UM CONJUNTO DE CLIENTES ASSOCIADOS. ISSO PODE SER REPRESENTADO COMO UMA AGREGAÇÃO.


class Cliente:
    def __init__(self,cpf,nome,endereço):
        self.cpf = cpf
        self.nome = nome
        self.endereço = endereço
        
